### ISSUE TITLE
Hide point when only have one page

### ISSUE THREAD

**Issue by rafa-aguilar** [sheikalthaf/ngx-carousel#39]
Hi,

Is possible to hide the point when only have one page? I think that this an error but can be something configurable.

Example:

```javascript
this.carouselConfig = {
  grid: {xs: 1, sm: 1, md: 3, lg: 3, all: 0},
  slide: 1,
  speed: 400,
  interval: 10000,
  point: {
    visible: true
  },
  touch: true,
  loop: true
};
```

With 3 items on carousel:

xs: 3 pages = 3 points [Correct]
sm: 3 pages = 3 points [Correct]
md: 1 page = 1 point [Error - no points]
lg: 1 page = 1 point [Error - no points]

Thanks!

**Comment by sheikalthaf** [comment]
Duplicate of #33

**Comment by rafa-aguilar** [comment]
Sorry but this issue is not about the arrows as the #33 , this issue talks about the points that shows the pages.

**Comment by sheikalthaf** [comment]
@rafa-aguilar This issue is fixed in build v1.3.0. I tried your `config`. but I didn't get any issue with the point.
which build you are using

**Comment by rafa-aguilar** [comment]
@sheikalthaf I've just updated and the "problem" still happens.

I'm not sure if I explained correctly: The case is when have only one page with my config the ngx-carousel is showing one point (the ones that show to the users the active/total pages), but I think that point needs to be hide.

I'm going to do a plunkr to show the problem.

**Comment by rafa-aguilar** [comment]
https://plnkr.co/edit/zshG5a?p=preview

![screen shot 2017-11-08 at 13 28 54](https://user-images.githubusercontent.com/594574/32549383-8af0c186-c489-11e7-863b-dcebf6a7a15f.png)
![screen shot 2017-11-08 at 13 29 05](https://user-images.githubusercontent.com/594574/32549384-8b0dd0b4-c489-11e7-8ce1-9b13d8b72be7.png)

**Comment by sheikalthaf** [comment]
@rafa-aguilar I think you don't need any point when there are no slide remains. but without points, it looks like a static image.
Anyway, I have fixed it. I will push the update if possible

**Comment by rafa-aguilar** [comment]
@sheikalthaf yes it just what I mean!! 
Thanks a lot!

**Comment by iamlothian** [comment]
Potentially this settings should be optional.

**Comment by sheikalthaf** [comment]
@iamlothian @rafa-aguilar sure

**Comment by rafa-aguilar** [comment]
@sheikalthaf @iamlothian yes, I mentioned it when I opened this issue

**Comment by rafa-aguilar** [comment]
@sheikalthaf any update? If you need a PR I can do!

**Comment by sheikalthaf** [comment]
@rafa-aguilar @iamlothian  Update now available v1.3.3. In point use `hideOnSingleSlide: boolean`
```javascript
point: {
        visible: true,
        hideOnSingleSlide: true
},
```
after successfull testing close this issue.
thanks for the support

**Comment by rafa-aguilar** [comment]
@sheikalthaf thank you so much!
